<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27603" started-at="2015-08-29T17:17:26Z" finished-at="2015-08-29T17:17:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27603" started-at="2015-08-29T17:17:26Z" finished-at="2015-08-29T17:17:54Z">
      <class name="RestService.TestMD5">
        <test-method status="PASS" signature="test()[pri:0, instance:RestService.TestMD5@174a1c22]" name="test" duration-ms="3300" started-at="2015-08-29T22:47:26Z" finished-at="2015-08-29T22:47:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="test2()[pri:0, instance:RestService.TestMD5@174a1c22]" name="test2" duration-ms="23579" started-at="2015-08-29T22:47:29Z" finished-at="2015-08-29T22:47:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="FAIL" signature="test3()[pri:0, instance:RestService.TestMD5@174a1c22]" name="test3" duration-ms="700" started-at="2015-08-29T22:47:53Z" finished-at="2015-08-29T22:47:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Doe] but found [Smith]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Doe] but found [Smith]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at RestService.TestMD5.test3(TestMD5.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
      </class> <!-- RestService.TestMD5 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
